<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="31846" started-at="2021-02-04T07:40:10Z" finished-at="2021-02-04T07:40:42Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="31846" started-at="2021-02-04T07:40:10Z" finished-at="2021-02-04T07:40:42Z">
      <class name="pac.Login">
        <test-method status="PASS" signature="login1()[pri:0, instance:pac.Login@457e2f02]" name="login1" duration-ms="9775" started-at="2021-02-04T13:10:32Z" finished-at="2021-02-04T13:10:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
      </class> <!-- pac.Login -->
      <class name="pac.HomePage">
        <test-method status="FAIL" signature="login1()[pri:0, instance:pac.HomePage@1b604f19]" name="login1" duration-ms="22021" started-at="2021-02-04T13:10:10Z" finished-at="2021-02-04T13:10:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Book Bus Travels, AC Volvo Bus, rPool & Bus Hire - redBus India] but found [Book Bus Travels, AC Volvo Bus, rPool & Bus Hire - redBus Indi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Book Bus Travels, AC Volvo Bus, rPool & Bus Hire - redBus India] but found [Book Bus Travels, AC Volvo Bus, rPool & Bus Hire - redBus Indi]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at pac.HomePage.login1(HomePage.java:20)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
      </class> <!-- pac.HomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
